name: My Workflow
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: echo "The current date is $(date)"
  job2:
    runs-on: windows-latest
    steps:
      - name: Print Date
        run: echo "The actual date is $(date)"
  job3:
    runs-on: macos-latest
    steps:
      - name: Print Date
        run: echo "today's date is $(date)"
  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Job 4
        run: echo "This is Job 4"
